### ISSUE TITLE
Swig on MacOs

### ISSUE THREAD

**Issue by Pampastu** [world-federation-of-advertisers/any-sketch-java#9]
I ran into the problem that when trying to build a project, basel does not detect swig, although it is installed and when entering a command in swig in the terminal, it is determined. Maybe someone from your team has already encountered this and can tell you how to solve it? Searching the internet didn't help

**swag was installed with homebrew**

Check swig installation:

```
swig -version

SWIG Version 4.0.2

Compiled with clang++ [arm-apple-darwin21.1.0]

Configured options: +pcre

Please see http://www.swig.org for reporting bugs and further information
```

Attempt to build a project

```
bazel build //...                                          
INFO: Analyzed 32 targets (0 packages loaded, 0 targets configured).
INFO: Found 32 targets...
ERROR: /Users/dmitrymakarevich/Desktop/Work/460_LiquidLegions_/any-sketch-java/src/main/java/org/wfanet/anysketch/crypto/BUILD.bazel:6:13: SwigCompile src/main/java/org/wfanet/anysketch/crypto/sketch_encrypter_adapter.cc failed: (Exit 127): mkdir_wrapper failed: error executing command bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/wfa_rules_swig/tools/mkdir_wrapper bazel-out/darwin_arm64-fastbuild/bin/src/main/java/org/wfanet/anysketch/crypto/java_files swig -c++ -java ... (remaining 21 argument(s) skipped)
bazel-out/darwin_arm64-opt-exec-2B5CBBC6/bin/external/wfa_rules_swig/tools/mkdir_wrapper: line 27: exec: swig: not found
INFO: Elapsed time: 0.282s, Critical Path: 0.15s
INFO: 17 processes: 9 internal, 8 local.
FAILED: Build did NOT complete successfully
```

**Comment by SanjayVas** [comment]
This is part of the larger Cross-Media Measurement project, which is only intended to be built on Linux. See https://github.com/world-federation-of-advertisers/cross-media-measurement/blob/main/docs/building.md

**Comment by SanjayVas** [comment]
Note that the proper path to address this would likely be configuring a SWIG toolchain in https://github.com/world-federation-of-advertisers/rules_swig.

**Comment by Pampastu** [comment]
Thank you so much for your help, if I find a solution, I will post it here
